global:
  scrape_interval: 15s
scrape_configs:
- job_name: cadvisor
  honor_timestamps: false
  static_configs:
  - targets:
    - cadvisor:8081
- job_name: vmetrics
  static_configs:
  - targets:
    - victoriametrics:8428
