apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    withCredentials: false
    isDefault: false
    version: 1
    editable: true
  - name: VM
    type: prometheus
    access: proxy
    orgId: 1
    url: http://victoriametrics:8428
    basicAuth: false
    withCredentials: false
    isDefault: true
    version: 1
    editable: true
